bookshop/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('book/list/', views.BookListView.as_view(), name='book_list'),
    path('book/<slug:slug>/detail/', views.BookDetailView.as_view(), name='book_detail'),

    path('book/create/', views.BookCreateView.as_view(), name='book_create'),
    path('book/<slug:slug>/update/', views.BookUpdateView.as_view(), name='book_update'),
    path('book/<slug:slug>/delete/', views.BookDeleteView.as_view(), name='book_delete'),

    path('cart/', views.CartListView.as_view(), name='cart_list'),
    path('cart/<int:pk>/add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/<int:pk>/remove/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/<int:pk>/delete/', views.CartDeleteView.as_view(), name='cart_delete'),

    path('product/<slug:slug>/comment/', views.CommentView.as_view(), name='comment'),


    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookshop.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/update/photo/', views.UpdateProfileImageView.as_view(), name='update_photo'),
    path('profile/update/password/', views.PasswordChangeView.as_view(), name='password_change'),
    path('profile/update/info/', views.UpdateProfileView.as_view(), name='update_info'),
    path('register/', views.Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.ActivateAccount.as_view(), name='activate'),
    path('activate/resend-activation/', views.ResendActivationEmail.as_view(), name='resend_activation_email'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

bookshop/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField

from user.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nomi")
    slug = models.SlugField(max_length=100, verbose_name="Slug")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan vaqti")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Kategoriya'
        verbose_name_plural = 'Kategoriyalar'


class Book(models.Model):
    title = models.CharField(max_length=200, verbose_name="Nomi")
    slug = models.SlugField(max_length=200, verbose_name="Slug")
    author = models.CharField(max_length=100, verbose_name="Muallif")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Kategoriya")
    publication_year = models.IntegerField(verbose_name="Yili")
    description = models.TextField(verbose_name="Tavsif")
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Narxi (so'm)")
    is_discount = models.BooleanField(default=False, verbose_name="Chegirmadami?")
    discount = models.DecimalField(max_digits=4, decimal_places=2, default=0, verbose_name="Chegirish qiymati (%)")
    image = models.ImageField(upload_to='books/', verbose_name="Rasmi")
    quantity = models.IntegerField(verbose_name="Soni")
    views = models.IntegerField(default=0, verbose_name="Ko'rishlar")
    is_featured = models.BooleanField(default=False, verbose_name="Tavsiya qilinsinmi?")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Yangilangan vaqti")
    full_description = RichTextField(null=True, blank=True, default="Yo'q", verbose_name="Tavsif")

    def __str__(self):
        return self.author + ' - ' + self.title

    def get_image(self):
        if self.image:
            return self.image.url
        return None

    class Meta:
        verbose_name = 'Kitob'
        verbose_name_plural = 'Kitoblar'
        ordering = ['-created_at']

    def current_price(self):
        if self.is_discount:
            return round(self.price * (1 - self.discount / 100), 2)
        return self.price

    def get_rating(self):
        comments = self.comment_set.all()
        if comments.exists():
            return '{:.2f}'.format(sum(comment.rating for comment in comments) / comments.count())
        return 0

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Book, self).save(*args, **kwargs)


class Comment(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name="Kitob")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Foydalanuvchi")
    rating = models.IntegerField(default=0, verbose_name="Baho")
    content = models.TextField(verbose_name="Izoh")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqtih")

    def __str__(self):
        return self.user.username +'-'+ self.book.title

    class Meta:
        verbose_name = 'Izoh'
        verbose_name_plural = 'Izohlar'

bookshop/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Book
from ckeditor.widgets import CKEditorWidget
from ckeditor.fields import RichTextFormField

class BookForm(forms.ModelForm):
    full_description = forms.CharField(widget=CKEditorWidget(), required=False)
    class Meta:
        model = Book
        fields = ['title', 'slug', 'author', 'category', 'publication_year', 'description', 'price',
                  'is_discount', 'discount', 'image', 'quantity', 'is_featured', 'full_description']

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price <= 0:
            raise forms.ValidationError("Narx musbat bo'lishi kerak.")
        return price

    def clean_discount(self):
        discount = self.cleaned_data.get('discount')
        if discount < 0 or discount > 100:
            raise forms.ValidationError("Chegirma foizi 0 va 100 orasida bo'lishi kerak.")
        return discount

    def clean_quantity(self):
        quantity = self.cleaned_data.get('quantity')
        if quantity < 0:
            raise forms.ValidationError("Kitob soni manfiy bo'lmasligi kerak.")
        return quantity

    def update(self, book_instance):
        book_instance.title = self.cleaned_data.get('title')
        book_instance.slug = self.cleaned_data.get('slug')
        book_instance.author = self.cleaned_data.get('author')
        book_instance.category = self.cleaned_data.get('category')
        book_instance.publication_year = self.cleaned_data.get('publication_year')
        book_instance.description = self.cleaned_data.get('description')
        book_instance.price = self.cleaned_data.get('price')
        book_instance.is_discount = self.cleaned_data.get('is_discount')
        book_instance.discount = self.cleaned_data.get('discount')
        if self.cleaned_data.get('image'):
            book_instance.image = self.cleaned_data.get('image')
        book_instance.cart_quantity = self.cleaned_data.get('quantity')
        book_instance.is_featured = self.cleaned_data.get('is_featured')

        book_instance.save()
        return book_instance



class CommentForm(forms.Form):
    rating = forms.IntegerField(
        required=True,
        label="Your Rating",
        min_value=1,
        max_value=5,
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'id': 'rating',
            'min': '1',
            'max': '5',
            'type': 'hidden',
            'value': 1
        })
    )

    content = forms.CharField(
        required=True,
        label="Your Review",
        widget=forms.Textarea(attrs={
            'class': 'form-control w-100',
            'id': 'content',
            'rows': 9,
            'cols': 30,
            'name': 'content',
            'placeholder': 'Izohingiz...'
        })
    )

    def clean_rating(self):
        rating = self.cleaned_data.get('rating')
        if not (1 <= rating <= 5):
            raise ValidationError("Mahsulotni 1 dan 5gacha baholang")
        return rating

bookshop/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.db import models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.contrib import messages

from .forms import CommentForm, BookForm
from .models import Category, Book, Comment


class HomeView(View):
    def get(self, request):
        books = Book.objects.all()
        featured_books = Book.objects.filter(is_featured=True)[:8]
        popular = Book.objects.annotate(avg_rating=models.Avg('comment__rating')) \
                              .order_by('-avg_rating')[:8]
        new_books = books.order_by('-created_at')[:8]

        context = {
            'title': 'Bosh sahifa',
            'page_name': 'Home',
            'books': books,
            'featured_books': featured_books,
            'popular_books': popular,
            'new_books': new_books,
        }
        return render(request, 'bookshop/index.html', context)


class BookListView(View):
    def get(self, request):
        category_slug = request.GET.get('category', None)
        if category_slug:
            selected_category = Category.objects.filter(slug=category_slug).first()
            if not selected_category:
                return redirect('book:book_list')
            books = Book.objects.filter(category=selected_category)
        else:
            selected_category = None
            books = Book.objects.all()
        context = {
            'title': 'Barcha kitoblar' if selected_category is None else selected_category.name,
            'page_name': 'Book List',
            'books': books,
            'selected_category': "Barchasi" if selected_category is None else selected_category,
        }
        return render(request, 'bookshop/book_list.html', context)


class BookDetailView(View):
    def get(self, request, slug):
        comment_form = CommentForm()
        book = Book.objects.filter(slug=slug).first()
        cart = request.session.get('cart')
        if cart:
            book_cart_quantity = cart.get(str(book.pk), 0)
        else:
            book_cart_quantity = 0
        if not book:
            return redirect('book:book_list')
        context = {
            'title': book.title,
            'page_name': 'Book Detail',
            'book': book,
            'comment_form': comment_form,
            'book_cart_quantity': book_cart_quantity,
        }
        return render(request, 'bookshop/book_detail.html', context)


class BookCreateView(View):
    def get(self, request):
        form = BookForm()
        return render(request, 'bookshop/book_form.html', {'form': form})

    def post(self, request):
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Kitob muvaffaqiyatli qo'shildi!")
            return redirect('book:book_list')
        return render(request, 'bookshop/book_form.html', {'form': form, 'title': 'QO\'shish'})



class BookUpdateView(View):
    def get(self, request, slug):
        book = Book.objects.get(slug=slug)
        form = BookForm(instance=book)
        return render(request, 'bookshop/book_form.html', {'form': form, 'title': 'Yangilash'})

    def post(self, request, slug):
        book = Book.objects.get(slug=slug)
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            messages.success(request, "Kitob muvaffaqiyatli tahrirlandi!")
            return redirect('book:book_detail', slug=book.slug)
        return render(request, 'bookshop/book_form.html', {'form': form})


class BookDeleteView(View):
    def get(self, request, slug):
        book = Book.objects.get(slug=slug)
        book.delete()
        messages.success(request, "Kitob muvaffaqiyatli o'chirildi!")
        return redirect('book:book_list')


class CommentView(LoginRequiredMixin, View):
    def post(self, request, slug):
        book = Book.objects.get(slug=slug)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            Comment.objects.create(
                content=comment_form.cleaned_data['content'],
                rating=comment_form.cleaned_data['rating'],
                user=request.user,
                book=book,
            )
        return redirect('book:book_detail', slug=slug)


class AboutView(View):
    def get(self, request):
        context = {
            'title': 'Haqida',
            'page_name': 'About',
        }
        return render(request, 'bookshop/about.html', context)


class ContactView(View):
    def get(self, request):
        context = {
            'title': 'Bog\'lanish',
            'page_name': 'Contact',
        }
        return render(request, 'bookshop/contact.html', context)


class CartListView(View):
    def get(self, request):
        cart = request.session.get('cart', {})
        books = Book.objects.filter(id__in=cart.keys())
        full_price = 0
        for book in books:
            book.cart_quantity = cart[str(book.id)]
            book.total_price = float(book.current_price()) * cart[str(book.id)]
            full_price += book.total_price
        context = {
            'title': 'Savat',
            'books': books,
            'full_price': full_price,
        }
        return render(request,'bookshop/cart_list.html', context)


class CartAddView(View):
    def get(self, request, pk):
        cart = request.session.get('cart', {})
        p_id = str(pk)

        if cart.get(p_id):
            cart[p_id] += 1
            message = "Cart yangilandi"
        else:
            cart[p_id] = 1
            message = "Cartga qo'shildi"

        request.session['cart'] = cart
        return JsonResponse({'status': 'success', 'cart': cart, 'message': message})


class CartRemoveView(View):
    def get(self, request, pk):
        cart = request.session.get('cart', {})
        p_id = str(pk)
        p = cart.get(p_id)
        if p:
            if p > 1:
                cart[p_id] -= 1
                message = "Cart yangilandi"
            elif p == 1:
                del cart[p_id]
                message = "Cartdan o'chirildi"
            else:
                message = "Mavjud emas"
        else:
            message = "Cartda mavjud emas"
        request.session['cart'] = cart
        return JsonResponse({'status': 'success', 'cart': cart, 'message': message})


class CartDeleteView(View):
    def get(self, request, pk):
        cart = request.session.get('cart', {})
        p_id = str(pk)
        if p_id in cart:
            del cart[p_id]
        request.session['cart'] = cart
        return redirect('book:cart_list')

bookshop/templates/bookshop/about.html
{% extends 'base.html' %}

{% block content %}
    <section class="section-padding">
        <div class="container pt-25">
            <div class="row">
                <div class="col-lg-6 align-self-center mb-lg-0 mb-4">
                    <h6 class="mt-0 mb-15 text-uppercase font-sm text-brand wow fadeIn animated">Bizning Do'kon</h6>
                    <h1 class="font-heading mb-40">
                        Kitob Olamiga Yo'l Ochamiz
                    </h1>
                    <p>Eng so'nggi nashrlar va betakror kitoblar to'plami bilan sizni kutib olishdan mamnunmiz. Bizning kitoblar sizni yangi bilimlar olamiga olib kiradi.</p>
                    <p>Do'konimizda turli janrlardagi kitoblar mavjud: badiiy adabiyot, ilmiy kitoblar, bolalar adabiyoti va yana ko'p narsalar. Har qanday kitobxon uchun o'ziga xos tanlov bor!</p>
                </div>
                <div class="col-lg-6">
                    <img src="https://www.anglicannews.org/media/1345762/black_web_booksonline.jpg" alt="Kitob do'koni rasm">
                </div>
            </div>
        </div>
    </section>
{% endblock %}

bookshop/templates/bookshop/book_list.html
{% extends 'base.html' %}

{% block content %}
    <section class="mt-50 mb-50">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shop-product-fillter">
                    {% if request.user.is_authenticated and request.user.is_staff %}
                        <a class="btn" href="{% url 'book:book_create' %}"><i class="fi-rs-add"> </i> Kitob qo'shish</a>
                    {% endif %}

                        <div class="totall-product">
                            <p> Siz uchun <strong class="text-brand">{{ books.count }} ta</strong> kitob topildi!</p>
                        </div>


                        <div class="sort-by-product-area">
                            <div class="sort-by-cover mr-10">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps"></i>Kategoriya:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> {{ selected_category }} <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="{% if selected_category == "Barchasi" %}active{% endif %}" href="{% url 'book:book_list' %}">Barchasi</a></li>
                                        {% for category in categories %}
                                            <li><a class="{% if selected_category.slug == category.slug %}active{% endif %}" href="{% url 'book:book_list' %}?category={{ category.slug }}">{{ category }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row product-grid-3">
                        {% for book in books %}
                            {% include 'bookshop/_components/book_card.html' %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

bookshop/templates/bookshop/cart_list.html
{% extends 'base.html' %}

{% block content %}
    <section class="mt-50 mb-50">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive">
                        <table class="table shopping-summery text-center clean">
                            <thead>
                            <tr class="main-heading">
                                <th scope="col">Rasm</th>
                                <th scope="col">Nomi</th>
                                <th scope="col">Narx</th>
                                <th scope="col">Soni</th>
                                <th scope="col">Umumiy narxi</th>
                                <th scope="col">Amallar</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for book in books %}
                                <tr>
                                    <td class="image product-thumbnail" data-title="Rasmi: "><img src="{{ book.get_image }}" alt="#">
                                    </td>
                                    <td class="product-des product-name" data-title="Nomi: ">
                                        <h5 class="product-name">
                                            <a href="{% url 'book:book_detail' book.slug %}">
                                                {{ book.title }}
                                            </a>
                                        </h5>
                                    </td>
                                    <td class="price" data-title="Narxi: "><span>{{ book.current_price }} so'm</span></td>
                                    <td class="text-center" data-title="Soni: ">
                                        <div class="detail-qty border radius">
                                            <a id="btn_minus" href="#" class="qty-down" onclick="updateCart(event, 'remove', '{{ book.pk }}'); showButton()">
                                                <i class="fi-rs-angle-small-down"></i>
                                            </a>
                                            <span id="qty_val{{ book.pk }}" class="qty-val">{{ book.cart_quantity }}</span>
                                            <a href="#" class="qty-up" onclick="updateCart(event, 'add', '{{ book.pk }}'); showButton()">
                                                <i class="fi-rs-angle-small-up"></i>
                                            </a>
                                        </div>
                                    </td>
                                    <td class="text-right" data-title="Umumiy narx: ">
                                        <span>{{ book.total_price }} so'm</span>
                                    </td>
                                    <td class="action" data-title="Amallar: ">
                                        <a href="{% url 'book:cart_delete' book.pk %}" aria-label="Savatdan o'chirish">
                                            <i class="fi-rs-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        {% if not books %}
                            <h4 class="text-center">
                                Savatingiz bo'sh, <a href="{% url 'book:book_list' %}">Kitoblar olamiga o'ting :)</a>
                            </h4>
                        {% endif %}
                    </div>
                    <div class="cart-action text-end">
                        <a id="cart_update" href="{% url 'book:cart_list' %}" class="disabled btn  mr-10 mb-sm-15"><i class="fi-rs-shuffle mr-10"></i>Update Cart</a>
                        <a class="btn mb-sm-15"><i class="fi-rs-shopping-bag mr-10"></i>Continue Shopping</a>
                    </div>
                    <div class="divider center_icon mt-50 mb-50"><i class="fi-rs-fingerprint"></i></div>
                    <div class="row mb-50">
                        <div class="col-lg-6 col-md-12">
                            <div class="heading_s1 mb-3">
                                <h4>Calculate Shipping</h4>
                            </div>
                            <p class="mt-15 mb-30">Flat rate: <span class="font-xl text-brand fw-900">5%</span></p>
                            <form class="field_form shipping_calculator">
                                <div class="form-row">
                                    <div class="form-group col-lg-12">
                                        <div class="custom_select">
                                            <label>
                                                <select class="form-control select-active">
                                                    <option value="">Tanlash...</option>
                                                    <option value="Uz">O'zbekiston</option>
                                                </select>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row row">
                                    <div class="form-group col-lg-6">
                                        <input required="required" placeholder="State / Country" name="name"
                                               type="text">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <input required="required" placeholder="PostCode / ZIP" name="name" type="text">
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-lg-12">
                                        <button class="btn  btn-sm"><i class="fi-rs-shuffle mr-10"></i>Update</button>
                                    </div>
                                </div>
                            </form>
                            <div class="mb-30 mt-50">
                                <div class="heading_s1 mb-3">
                                    <h4>Apply Coupon</h4>
                                </div>
                                <div class="total-amount">
                                    <div class="left">
                                        <div class="coupon">
                                            <form action="#" target="_blank">
                                                <div class="form-row row justify-content-center">
                                                    <div class="form-group col-lg-6">
                                                        <input class="font-medium" name="Coupon"
                                                               placeholder="Enter Your Coupon">
                                                    </div>
                                                    <div class="form-group col-lg-6">
                                                        <button class="btn  btn-sm"><i class="fi-rs-label mr-10"></i>Apply
                                                        </button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-12">
                            <div class="border p-md-4 p-30 border-radius cart-totals">
                                <div class="heading_s1 mb-3">
                                    <h4>Cart Totals</h4>
                                </div>
                                <div class="table-responsive">
                                    <table class="table">
                                        <tbody>
                                        <tr>
                                            <td class="cart_total_label">Cart Subtotal</td>
                                            <td class="cart_total_amount"><span class="font-lg fw-900 text-brand">{{ full_price|floatformat:2 }} so'm</span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="cart_total_label">Shipping</td>
                                            <td class="cart_total_amount"><i class="ti-gift mr-5"></i> Free Shipping
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="cart_total_label">Total</td>
                                            <td class="cart_total_amount"><strong><span
                                                    class="font-xl fw-900 text-brand">{{ full_price|floatformat:2 }} so'm</span></strong></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <a href="#" class="btn "> <i class="fi-rs-box-alt mr-10"></i> Proceed To CheckOut</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script>
        function showButton() {
            const button = document.getElementById('cart_update');
            button.classList.remove('disabled');
        }
    </script>
{% endblock %}

bookshop/templates/bookshop/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    {% include 'components/slider.html' %}

    {% include 'components/featured.html' %}

    {% include 'components/books.html' %}

    {% include 'components/categories.html' %}
{% endblock %}