config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookshop.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/update/photo/', views.UpdateProfileImageView.as_view(), name='update_photo'),
    path('profile/update/password/', views.PasswordChangeView.as_view(), name='password_change'),
    path('profile/update/info/', views.UpdateProfileView.as_view(), name='update_info'),
    path('register/', views.Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.ActivateAccount.as_view(), name='activate'),
    path('activate/resend-activation/', views.ResendActivationEmail.as_view(), name='resend_activation_email'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users/profile/', null=True, blank=True)
    phone = models.CharField(max_length=13, null=True, blank=True)
    address = models.CharField(max_length=150, null=True, blank=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'Foydalanuvchi'
        verbose_name_plural = 'Foydalanuvchilar'

    def get_image(self):
        if self.image:
            return self.image.url
        return "https://png.pngitem.com/pimgs/s/111-1114675_user-login-person-man-enter-person-login-icon.png"

user/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import PasswordResetTokenGenerator, default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, EmailMessage
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode, urlencode
from django.views.generic import View, FormView
from django.contrib import messages
from .forms import RegisterForm, LoginForm, UpdateProfileForm, PasswordChangeForm, ResetPasswordForm, SetNewPasswordForm
from .models import User
from django.contrib.auth import update_session_auth_hash



class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        profile_form = UpdateProfileForm(instance=request.user)
        password_form = PasswordChangeForm()
        context = {
            'profile_form': profile_form,
            'password_form': password_form,
            'title': 'Profilim',
            'page_name': 'Profile',
        }
        return render(request, 'user/profile.html', context)

    def post(self, request):
        return redirect('user:profile')


class UpdateProfileImageView(LoginRequiredMixin, View):
    def post(self, request):
        if 'image' in request.FILES:
            image = request.FILES['image']
            if image.name.endswith(('.jpg', '.jpeg', '.png')):
                user = request.user
                user.image = image
                user.save()
                messages.success(request, 'Profil rasmi o\'zgartirildi!')
            else:
                messages.error(request, 'Noto\'g\'ri fayl formati. JPG, JPEG yoki PNG formatidagi rasmni tanlang.')
                return redirect('user:profile')
        messages.error(request, 'Rasmni yuklashda xato!')
        return redirect('user:profile')


class PasswordChangeView(LoginRequiredMixin, View):
    def get(self, request):
        context = {
            'title': 'Parolni yangilash',
            'password_form': PasswordChangeForm(),
        }
        return render(request, 'user/password_change.html', context)
    def post(self, request):
        user = get_object_or_404(User, id=request.user.id)
        password_form = PasswordChangeForm(request.POST)
        password_form.set_user(self.request.user)

        if password_form.is_valid():
            new_password = password_form.cleaned_data['new_password']
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Parolingiz yangilandi!")
            return redirect('user:profile')

        context = {
            'title': 'Parolni yangilash - Student Office',
            'password_form': password_form,
            'profile_form': UpdateProfileForm(),
        }
        return render(request, 'user/password_change.html', context)


class UpdateProfileView(LoginRequiredMixin, View):
    def get(self, request):
        context = {
            'profile_form': UpdateProfileForm(instance=request.user),
            'title': "Ma'lumotlarni tahrirlash",
        }
        return render(request, 'user/personal_information.html', context)

    def post(self, request):
        profile_form = UpdateProfileForm(self.request.POST, instance=request.user)

        if profile_form.is_valid():
            email = profile_form.cleaned_data['email']
            phone = profile_form.cleaned_data['phone']

            if email:
                request.user.email = email
            if phone:
                request.user.phone = phone
            request.user.first_name = profile_form.cleaned_data['first_name']
            request.user.last_name = profile_form.cleaned_data['last_name']
            request.user.address = profile_form.cleaned_data['address']
            request.user.save()
            messages.success(request, "Ma'lumotlar muvafaqqiyatli yangilandi!")
            return redirect('user:profile')

        context = {
            'profile_form': profile_form,
            'title': 'Profilim',
            'page_name': 'Profile',
        }
        return render(request, 'user/personal_information.html', context)


class ResetPasswordView(View):
    def get(self, request):
        context = {
            'title': "Parolni unutdim",
            'reset_form': ResetPasswordForm(),
        }
        return render(request, 'user/password_reset.html', context)

    def post(self, request):
        reset_form = ResetPasswordForm(request.POST)
        if reset_form.is_valid():
            email = reset_form.cleaned_data['email']
            user = User.objects.get(email=email)
            token_generator = PasswordResetTokenGenerator()

            token = token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))

            reset_link = reverse_lazy('user:password_reset_confirm', kwargs={'uidb64': uid, 'token': token})
            reset_url = self.request.build_absolute_uri(reset_link)

            email_subject = 'Parolingizni qayta tiklash'
            email_body = "Sizning emailingizga parolni qayta tiklash uchun so'rovingiz asosida link yuborildi."\
                f"Link: {reset_url} "\
                "Ushbu link orqali parolingizni almashtirishingiz mumkin"

            send_mail(
                email_subject, email_body,
                None, [user.email],
                fail_silently=False,
            )
            messages.success(request, "Sizning emailingizga parol almashtirish uchun link va qo'llanma yuborildi.")
            return redirect('book:home')


        context = {
            'title': "Parolni unutdim",
            'reset_form': reset_form,
        }
        return render(request, 'user/password_reset.html', context)


class PasswordResetConfirmView(FormView):
    template_name = 'user/password_reset_confirm.html'
    form_class = SetNewPasswordForm
    success_url = reverse_lazy('user:login')

    def dispatch(self, request, *args, **kwargs):
        self.uidb64 = kwargs['uidb64']
        self.token = kwargs['token']
        self.user = self.get_user()

        token_generator = PasswordResetTokenGenerator()
        if self.user is not None and token_generator.check_token(self.user, self.token):
            return super().dispatch(request, *args, **kwargs)
        else:
            messages.error(request, "Bu link yaroqli emas!")
            return redirect('user:password_reset')

    def get_user(self):
        try:
            uid = urlsafe_base64_decode(self.uidb64).decode()
            return User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            return None

    def form_valid(self, form):
        new_password = form.cleaned_data['new_password']
        self.user.set_password(new_password)
        self.user.save()

        update_session_auth_hash(self.request, self.user)
        messages.success(self.request, "Parolingiz muvafaqqiyatli o'zgartirildi!")

        return super().form_valid(form)


class Register(View):
    def get(self, request):
        context = {
            'form': RegisterForm(),
            'title': "Ro'yxatdan o'tish",
        }
        return render(request, 'user/register.html', context)

    def post(self, request):
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.create_user()
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            subject = 'Ro\'yxatdan o\'tishni tasdiqlash'
            message = render_to_string('user/email_verification.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })

            email = EmailMessage(
                subject,
                message,
                'asatullayevblog@gmail.com',
                [user.email],
            )
            email.content_subtype = "html"
            email.send(fail_silently=True)

            messages.success(request, "Ro'yxatdan o'tdingiz! Tasdiqlash uchun emailingizni tekshiring.")
            return redirect('user:login')

        context = {
            'form': form,
            'title': "Ro'yxatdan o'tish",
        }
        return render(request, 'user/register.html', context)


class ActivateAccount(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            subject = 'Ro\'yxatdan o\'tishingiz muvaffaqiyatli tasdiqlandi!'
            message = render_to_string('user/verification_succes.html', {
                'full_name': user.get_full_name()
            })

            email = EmailMessage(
                subject,
                message,
                'asatullayevblog@gmail.com',
                [user.email],
            )
            email.content_subtype = "html"
            email.send(fail_silently=True)
            messages.success(request, "Sizning hisobingiz muvaffaqiyatli tasdiqlandi!")
            return redirect('user:login')
        else:
            messages.error(request, "Tasdiqlash havolasi yaroqsiz yoki muddati o'tgan.")
            return redirect('user:register')


class ResendActivationEmail(View):
    def get(self, request):

user/templates/user/email_verification.html
<p>Salom {{ user.get_full_name }},</p>
<p>Evara Book Shop`ga xush kelibsiz!</p>
<p>Ro'yxatdan o'tishingiz muvaffaqiyatli amalga oshdi. Sizdan, ro'yxatdan o'tishni tasdiqlash uchun quyidagi havolani bosish so'raladi:</p>
<a href="http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}">Tasdiqlash havolasi</a>
<p>Biz bilan bog'langaningiz uchun rahmat! Har qanday savollaringiz bo'lsa, bizga murojaat qiling.</p>
<p>Eng yaxshi tilaklar bilan,<br>Evara Book Shop jamoasi</p>

user/templates/user/login.html
{% extends 'base.html' %}

{% block content %}
    <section class="section-padding">
    <div class="user-area pt-100 pb-70">
        <div class="container">
            <div class="user-width mx-auto" style="max-width: 400px;">
                <div class="user-form shadow p-4 rounded bg-white">
                    <div class="contact-form">
                        <h2 class="text-center mb-4">Login Now</h2>

                        <!-- Non-field errors -->
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error|safe }}
                            </div>
                        {% endfor %}

                        <form method="post" action="{% url 'user:login' %}">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="username" class="form-label">Username</label>
                                {{ form.username }}
                                {% for error in form.username.errors %}
                                    <div class="text-danger">{{ error }}</div>
                                {% endfor %}
                            </div>

                            <div class="mb-3">
                                <label for="password" class="form-label">Password</label>
                                {{ form.password }}
                                {% for error in form.password.errors %}
                                    <div class="text-danger">{{ error }}</div>
                                {% endfor %}
                            </div>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary mb-2">
                                    Login
                                </button>
                                <a href="{% url 'user:register' %}" class="btn btn-dark mb-2">Register</a>
                                <a href="{% url 'user:password_reset' %}" class="text-primary float-end">Forgot password?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
{% endblock %}

user/templates/user/password_change.html
{% extends 'base.html' %}

{% block content %}
    <div class="container pb-3 pl-5 pr-5 mt-3">
        <div class="row gutters">
            <div class="col-md-6 offset-md-3 bg-white">
                <h1 class="mt-5">Parolni almashtirish</h1>
                <form method="post" name="changePassword" action="{% url 'user:password_change' %}">
                    {% csrf_token %}
                    {{ password_form }}
                    <div class="row mb-4">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <a href="{% url 'user:profile' %}" class="btn form-control btn-primary mt-3"
                               style="border-radius: 10px; color: black;">
                                <i class="fa fa-backward"></i> Cancel
                            </a>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <button type="submit" class="btn form-control btn-primary mt-3"
                                    style="border-radius: 10px;">
                                Saqlash
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends 'base.html' %}


{% block content %}
    <div class="user-area pt-100 pb-70">
        <div class="container">
            <div class="user-width mx-auto" style="max-width: 400px;">
                <div class="user-form shadow p-4 rounded bg-white">
                    <div class="contact-form">
                        <h2 class="text-center mb-4">Reset password</h2>

                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary">
                                    Send
                                </button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user/personal_information.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid mt-3">
        <div class="row gutters">
            <div class="col-md-6 offset-md-3 bg-white">
                <h1 class="mt-5">Tahrirlash</h1>
                <form method="post" name="changePassword" action="{% url 'user:update_info' %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="first_name">Ism:</label>
                                {{ profile_form.first_name }}
                                {% if profile_form.first_name.errors %}
                                    <div class="text-danger">
                                        {% for error in profile_form.first_name.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="last_name">Familiya:</label>
                                {{ profile_form.last_name }}
                                {% if profile_form.last_name.errors %}
                                    <div class="text-danger">
                                        {% for error in profile_form.last_name.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="email">Username:</label>
                                {{ profile_form.username }}
                                {% if profile_form.username.errors %}
                                    <div class="text-danger">
                                        {% for error in profile_form.username.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="email">Email:</label>
                                {{ profile_form.email }}
                                {% if profile_form.email.errors %}
                                    <div class="text-danger">
                                        {% for error in profile_form.email.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="phone">Telefon raqam:</label>
                                {{ profile_form.phone }}
                                {% if profile_form.phone.errors %}
                                    <div class="text-danger">
                                        {% for error in profile_form.phone.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="address">Manzil:</label>
                                {{ profile_form.address }}
                                {% if profile_form.address.errors %}
                                    <div class="text-danger">
                                        {% for error in profile_form.address.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="row mb-4">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <a href="{% url 'user:profile' %}" class="btn form-control mt-3"
                               style="border-radius: 10px; color: black;">
                                <i class="fa fa-backward"></i> Cancel
                            </a>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <button type="submit" class="btn form-control btn-primary mt-3"
                                    style="border-radius: 10px;">
                                Saqlash
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user/profile.html
{% extends 'base.html' %}

{% block content %}
    <section class="section-padding">
        <div class="container">
            <div class="row gutters px-xl-5">
                <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
                    <div class="card h-100">
                        <div class="card-body">
                            <div class="account-settings">
                                <div class="user-profile">
                                    <div class="user-avatar">
                                        <hr>
                                        <img id="userImage" src="{{ request.user.get_image }}" alt="User picture">
                                        <div class="image-icons">
                                            <div class="image-upload-icon"
                                                 onclick="document.getElementById('fileInput').click();">
                                                <i class="fa fa-camera"></i>
                                            </div>
                                        </div>
                                        <form id="imageForm" method="post" enctype="multipart/form-data"
                                              action="{% url 'user:update_photo' %}">
                                            {% csrf_token %}
                                            <input type="file" id="fileInput" name="image" accept=".jpg,.jpeg,.png"
                                                   style="display: none;"
                                                   onchange="document.getElementById('imageForm').submit();">
                                        </form>
                                    </div>
                                    <hr>
                                    <h5 class="user-name">{{ request.user.first_name }} {{ request.user.last_name }}</h5>
                                    <h6 class="user-email">{{ request.user.username }}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
                    <div class="card h-100 content-right">
                        <div class="card-body">
                            <hr>
                            <div class="row gutters">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <h6 class="mb-2 text-primary">Shaxsiy ma'lumotlar</h6>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label for="fullName">Ism Familiya</label>
                                        <input type="text" class="form-control" id="fullName" disabled
                                               value="{{ request.user.first_name }} {{ request.user.last_name }}">
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label for="phone">Email</label>
                                        <input type="text" class="form-control" id="phone" disabled
                                               value="{{ request.user.email }}">
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label for="website">Telefon:</label>
                                        <input type="url" class="form-control" id="website" disabled
                                               value="{{ request.user.phone }}">
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label for="sTate">Manzil</label>
                                        <input type="text" class="form-control" id="sTate" disabled
                                               value="{{ request.user.address }}">
                                    </div>
                                </div>
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <hr>
                                    <div class="row">
                                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                            <a href="{% url 'user:password_change' %}" class="btn form-control mt-3" style="border-radius: 10px;">
                                                <i class="fa fa-key"></i> Change password
                                            </a>
                                        </div>
                                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                            <a href="{% url 'user:update_info' %}" class="btn form-control mt-3" style="border-radius: 10px;">
                                                <i class="fa fa-user"></i> Edit personal information
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <style>
    .account-settings .user-profile {
        margin: 0 0 1rem 0;
        padding-bottom: 1rem;
        text-align: center;
    }

    .account-settings .user-profile .user-avatar {
        margin: 0 0 1rem 0;
    }

    .account-settings .user-profile .user-avatar img {
        width: 150px;
        height: 150px;
        -webkit-border-radius: 100px;
        -moz-border-radius: 100px;
        border-radius: 100px;
    }

    .account-settings .user-profile h5.user-name {
        margin: 0 0 0.5rem 0;
        font-size: 1.6rem;
    }

    .account-settings .user-profile h6.user-email {
        margin: 0;
        font-size: 1rem;
        color: #9fa8b9;
    }

    .account-settings .about {
        margin: 2rem 0 0 0;
        text-align: center;
    }

    .account-settings .about h5 {
        margin: 0 0 15px 0;
        color: #007ae1;
    }

    .form-control {
        border: 1px solid #cfd1d8;
        -webkit-border-radius: 2px;
        -moz-border-radius: 2px;
        border-radius: 5px;
        background: #ffffff;
        color: #2e323c;
    }

    .card {
        background: #ffffff;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        border: 0;
        margin-bottom: 1rem;
    }

    .change-password-pen:hover {
        color: #FFD333;
        transition: all .5s;
    }
</style>
{% endblock %}

user/templates/user/resend_activate.html
{% extends 'base.html' %}

{% block content %}
    <section class="section-padding">
    <div class="user-area pt-100 pb-70">
        <div class="container">
            <div class="user-width mx-auto" style="max-width: 400px;">
                <div class="user-form shadow p-4 rounded bg-white">
                    <div class="contact-form">
                        <h2 class="text-center mb-4">Account verification</h2>

                        <form method="post" action="{% url 'user:resend_activation_email' %}">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="email" class="form-label">Email</label>
                                <input id="email" type="email" name="email" required>
                            </div>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary mb-2">
                                    Verified
                                </button>
                                <a href="{% url 'user:login' %}" class="btn btn-dark mb-2">Login</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
{% endblock %}