bookshop/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('book/list/', views.BookListView.as_view(), name='book_list'),
    path('book/<slug:slug>/detail/', views.BookDetailView.as_view(), name='book_detail'),

    path('book/create/', views.BookCreateView.as_view(), name='book_create'),
    path('book/<slug:slug>/update/', views.BookUpdateView.as_view(), name='book_update'),
    path('book/<slug:slug>/delete/', views.BookDeleteView.as_view(), name='book_delete'),

    path('cart/', views.CartListView.as_view(), name='cart_list'),
    path('cart/<int:pk>/add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/<int:pk>/remove/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/<int:pk>/delete/', views.CartDeleteView.as_view(), name='cart_delete'),

    path('product/<slug:slug>/comment/', views.CommentView.as_view(), name='comment'),


    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookshop.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/update/photo/', views.UpdateProfileImageView.as_view(), name='update_photo'),
    path('profile/update/password/', views.PasswordChangeView.as_view(), name='password_change'),
    path('profile/update/info/', views.UpdateProfileView.as_view(), name='update_info'),
    path('register/', views.Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.ActivateAccount.as_view(), name='activate'),
    path('activate/resend-activation/', views.ResendActivationEmail.as_view(), name='resend_activation_email'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

templates/_components/footer.html
{% load static %}

<footer class="main">
    <section class="newsletter p-30 text-white wow fadeIn animated">
       
    </section>
    <section class="section-padding footer-mid">
        <div class="container pt-15 pb-20">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="widget-about font-md mb-md-5 mb-lg-0">
                        <div class="logo logo-width-1 wow fadeIn animated">
                            <a href="{% url 'book:home' %}"><img src="{% static 'bookshop/imgs/theme/logo.svg' %}"
                                                                 alt="logo"></a>
                        </div>
                        <h5 class="mt-20 mb-10 fw-600 text-grey-4 wow fadeIn animated">Aloqa</h5>
                        <p class="wow fadeIn animated">
                            <strong>Manzil: </strong>Farg'ona shahar, Farg'ona viloyati
                        </p>
                        <p class="wow fadeIn animated">
                            <strong>Telefon: </strong>+998-90-777-05-12
                        </p>
                        <p class="wow fadeIn animated">
                            <strong>Saat: </strong>10:00 - 18:00, Dush - Shan
                        </p>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3">
                    <h5 class="widget-title wow fadeIn animated">Haqida</h5>
                    <ul class="footer-list wow fadeIn animated mb-sm-5 mb-md-0">
                        <li><a href="{% url 'book:about' %}">Biz haqimizda</a></li>
                    </ul>
                    <h5 class="mb-10 mt-30 fw-600 text-grey-4 wow fadeIn animated">Bizni Kuzatish</h5>
                    <div class="mobile-social-icon wow fadeIn animated mb-sm-5 mb-md-0">
                        <a href="#"><img src="{% static 'bookshop/imgs/theme/icons/icon-facebook.svg' %}"
                                         alt=""></a>
                        <a href="#"><img src="{% static 'bookshop/imgs/theme/icons/icon-twitter.svg' %}" alt=""></a>
                        <a href="https://www.instagram.com/asatullayev0509" target="_blank"><img src="{% static 'bookshop/imgs/theme/icons/icon-instagram.svg' %}"
                                         alt=""></a>
                        <a href="#"><img src="{% static 'bookshop/imgs/theme/icons/icon-pinterest.svg' %}"
                                         alt=""></a>
                        <a href="#"><img src="{% static 'bookshop/imgs/theme/icons/icon-youtube.svg' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3">
                    <h5 class="widget-title wow fadeIn animated">Mening hisobim</h5>
                    <ul class="footer-list wow fadeIn animated">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'user:profile' %}">Profilim</a></li>
                            <li><a href="{% url 'user:logout' %}">Chiqish</a></li>
                        {% else %}
                            <li><a href="{% url 'user:login' %}">Kirish</a></li>
                            <li><a href="{% url 'user:register' %}">Ro'yxatdan o'tish</a></li>
                        {% endif %}
                        <li><a href="{% url 'book:cart_list' %}">Savatni ko'rish</a></li>
                    </ul>
                </div>
                <div class="col-lg-4">
                    <h5 class="widget-title wow fadeIn animated">Ilovani o'rnating</h5>
                    <div class="row">
                        <div class="col-md-8 col-lg-12">
                            <p class="wow fadeIn animated">App Store yoki Google Play'dan oling</p>
                            <div class="download-app wow fadeIn animated">
                                <a href="#" class="hover-up mb-sm-4 mb-lg-0"><img class="active"
                                                                                  src="{% static 'bookshop/imgs/theme/app-store.jpg' %}"
                                                                                  alt=""></a>
                                <a href="#" class="hover-up"><img
                                        src="{% static 'bookshop/imgs/theme/google-play.jpg' %}" alt=""></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="container pb-20 wow fadeIn animated">
        <div class="row">
            <div class="col-12 mb-20">
                <div class="footer-bottom"></div>
            </div>
            <div class="col-lg-6">
                <p class="float-md-left font-sm text-muted mb-0">&copy; 2024, <strong class="text-brand">Evara</strong>
                    -Online Kitob do'koni </p>
            </div>
            <div class="col-lg-6">
                <p class="text-lg-end text-start font-sm text-muted mb-0">
                    Dasturchi <a href="https://asatullayev.uz" target="_blank">Asatullayev Diyorbek</a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/_components/header.html
{% load static %}

<header class="header-area header-style-3 header-height-2">
    <div class="header-top header-top-ptb-1 d-none d-lg-block">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-3 col-lg-4">
                    <div class="header-info">
                        <ul>
                            <li><i class="fi-rs-smartphone"></i> <a href="#">+998 90 777 0512</a></li>
                            <li><i class="fi-rs-marker"></i><a href="{% url 'book:contact' %}">Bizning manzil</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-4">
                    <div class="text-center">
                        <div id="news-flash" class="d-inline-block">
                            <ul>
                                <li>Yangi kitoblar bilan tanishing! <a href="{% url 'book:book_list' %}">Batafsil</a></li>
                                <li>Maxsus takliflar - chegirmalar bilan xarid qiling!</li>
                                <li>Eng mashhur asarlar, bugun 30% gacha chegirmalar <a href="{% url 'book:book_list' %}">Xarid qiling</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4">
                    <div class="header-info header-info-right">
                        <ul>
                            <li>
                                <a class="language-dropdown-active" href="#"> <i class="fi-rs-world"></i> O'zbekcha <i
                                        class="fi-rs-angle-small-down"></i></a>
                                <ul class="language-dropdown">
                                    <li><a href="#">English</a></li>
                                    <li><a href="#">Pусский</a></li>
                                </ul>
                            </li>
                            {% if request.user.is_authenticated %}
                                <li><i class="fi-rs-user"></i><a href="{% url 'user:profile' %}">Profilim</a></li>
                                <li><i class="fi-rs-user-remove"></i><a href="{% url 'user:logout' %}">Chiqish</a></li>
                            {% else %}
                                <li><i class="fi-rs-user-time"></i><a href="{% url 'user:login' %}">Login</a></li>
                                <li><i class="fi-rs-user-add"></i><a href="{% url 'user:register' %}">Signin</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-middle header-middle-ptb-1 d-none d-lg-block">
        <div class="container">
            <div class="header-wrap">
                <div class="logo logo-width-1">
                    <a href="{% url 'book:home' %}"><img src="{% static 'bookshop/imgs/theme/logo.svg' %}" alt="logo"></a>
                </div>
                <div class="header-right">
                    <div class="search-style-2">
                        <form action="#">
                            <select class="select-active">
                                <option>Barchasi</option>
                                {% for category in categories %}
                                    <option>{{ category.name }}</option>
                                {% endfor %}
                            </select>
                            <input type="text" placeholder="Mahsulotlarni qidirish...">
                        </form>
                    </div>
                    <div class="header-action-right">
                        <div class="header-action-2">
                            <div class="header-action-icon-2">
                                <a class="mini-cart-icon" href="{% url 'book:cart_list' %}">
                                    <img alt="Evara" src="{% static 'bookshop/imgs/theme/icons/icon-cart.svg' %}">
                                    <span id="cart-count_top" class="pro-count blue">{{ request.session.cart|length }}</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-bottom header-bottom-bg-color sticky-bar">
        <div class="container">
            <div class="header-wrap header-space-between position-relative main-nav">
                <div class="logo logo-width-1 d-block d-lg-none">
                    <a href="{% url 'book:home' %}"><img src="{% static 'bookshop/imgs/theme/logo.svg' %}" alt="logo"></a>
                </div>
                <div class="header-nav d-none d-lg-flex">
                    <div class="main-categori-wrap d-none d-lg-block">
                        <a class="categori-button-active" href="#">
                            <span class="fi-rs-apps"></span> Kategoriyalarni ko'rish
                        </a>
                        <div class="categori-dropdown-wrap categori-dropdown-active-large">
                            <ul>
                                {% for category in categories %}
                                    <li><a href="{% url 'book:book_list' %}?category={{ category.slug }}">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="main-menu main-menu-padding-1 main-menu-lh-2 d-none d-lg-block">
                        <nav>
                            <ul>
                                <li><a class="{% if request.path == '/' %}active{% endif %}"
                                        href="{% url 'book:home' %}">Bosh sahifa</a></li>
                                <li><a class="{% if 'book/' in request.path %}active{% endif %}"
                                        href="{% url 'book:book_list' %}">Kitob do'koni</a></li>
                                <li><a class="{% if 'about/' in request.path %}active{% endif %}"
                                        href="{% url 'book:about' %}">Biz haqimizda</a></li>
                                <li><a class="{% if 'contact/' in request.path %}active{% endif %}"
                                        href="{% url 'book:contact' %}">Aloqa</a></li>
                            </ul>

                        </nav>
                    </div>
                </div>
                <div class="hotline d-none d-lg-block">
                    <p><i class="fi-rs-headset"></i><span>Support</span> 24 / 7</p>
                </div>
                <div class="header-action-right d-block d-lg-none">
                    <div class="header-action-2">
                        <div class="header-action-icon-2">
                            <a class="mini-cart-icon" href="{% url 'book:cart_list' %}">
                                <img alt="Evara" src="{% static 'bookshop/imgs/theme/icons/icon-cart.svg' %}">
                                <span id="cart-count_nav" class="pro-count white">{{ request.session.cart|length }}</span>
                            </a>
                        </div>
                        <div class="header-action-icon-2 d-block d-lg-none">
                            <div class="burger-icon burger-icon-white">
                                <span class="burger-icon-top"></span>
                                <span class="burger-icon-mid"></span>
                                <span class="burger-icon-bottom"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/_components/messages.html
<!-- Modal -->
<div class="container-fluid">
{% if messages %}
    {% for message in messages %}
        <div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        {% if message.tags == 'success' %}
                            <h5 class="modal-title text-uppercase" id="exampleModalLongTitle" style="color: green">
                                Muvafaqqiyatli!
                            </h5>
                        {% elif message.tags == 'warning' %}
                            <h5 class="modal-title text-uppercase" id="exampleModalLongTitle" style="color: orange">
                                Ogohlantirish!
                            </h5>
                        {% else %}
                            <h5 class="modal-title text-uppercase" id="exampleModalLongTitle" style="color: red">
                                Xatolik!
                            </h5>
                        {% endif %}
                    </div>
                    <div class="modal-body">
                        <p style="color: black">{{ message }}</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="close">Close</button>
                        <a href="{% url 'book:home' %}" type="button" class="btn btn-primary">Bosh sahifa</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}
</div>

<!-- Script to trigger modal on page load -->
{% if messages %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endif %}

<script>
$(document).ready(function(){
    $('#messageModal').modal('show');

    // close tugmasi bosilganda modalni yopish
    $('#close').on('click', function() {
        $('#messageModal').modal('hide');
    });
});
</script>

templates/_components/mobile_header.html
{% load static %}

<div class="mobile-header-active mobile-header-wrapper-style">
    <div class="mobile-header-wrapper-inner">
        <div class="mobile-header-top">
            <div class="mobile-header-logo">
                <a href="{% url 'book:home' %}"><img src="{% static 'bookshop/imgs/theme/logo.svg' %}" alt="logo"></a>
            </div>
            <div class="mobile-menu-close close-style-wrap close-style-position-inherit">
                <button class="close-style search-close">
                    <i class="icon-top"></i>
                    <i class="icon-bottom"></i>
                </button>
            </div>
        </div>
        <div class="mobile-header-content-area">
            <div class="mobile-search search-style-3 mobile-header-border">
                <form action="#">
                    <input type="text" placeholder="Kitoblar yoki mualliflar bo'yicha qidirish…">
                    <button type="submit"><i class="fi-rs-search"></i></button>
                </form>
            </div>
            <div class="mobile-menu-wrap mobile-header-border">
                <div class="main-categori-wrap mobile-header-border">
                    <a class="categori-button-active-2" href="#">
                        <span class="fi-rs-apps"></span> Kategoriyalar
                    </a>
                    <div class="categori-dropdown-wrap categori-dropdown-active-small">
                        <ul>
                            {% for category in categories %}
                                <li><a href="{% url 'book:book_list' %}?category={{ category.slug }}"><i class="evara-font-book"></i>{{ category.name }}</a></li>
                            {% endfor %}
                            
                        </ul>
                    </div>
                </div>
                <!-- mobil menyu boshlanishi -->
                <nav>
                    <ul class="mobile-menu">
                        <li class="menu-item-has-children"><span class="menu-expand"></span>
                            <a href="{% url 'book:home' %}">Bosh sahifa</a>
                        </li>
                        <li class="menu-item-has-children"><span class="menu-expand"></span><a href="#">Do'kon</a>
                            <ul class="dropdown">
                                <li><a href="{% url 'book:book_list' %}">Kitoblar</a></li>
                                <li><a href="{% url 'book:about' %}">Biz haqimizda</a></li>
                            </ul>
                        </li>
                        <li class="menu-item-has-children"><span class="menu-expand"></span><a href="#">Profilim</a>
                            <ul class="dropdown">
                                {% if request.user.is_authenticated %}
                                    <li><a href="{% url 'user:profile' %}">Profilim</a></li>
                                    <li><a href="{% url 'user:logout' %}">Chiqish</a>
                                    </li>
                                {% else %}
                                    <li><a href="{% url 'user:login' %}">Kirish</a></li>
                                    <li><a href="{% url 'user:register' %}">Ro'yxatdan o'tish</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="menu-item-has-children"><span class="menu-expand"></span><a href="#">Til</a>
                            <ul class="dropdown">
                                <li><a href="#">O'zbekcha</a></li>
                                <li><a href="#">Inglizcha</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <!-- mobil menyu tugashi -->
            </div>
            <div class="mobile-header-info-wrap mobile-header-border">
                <div class="single-mobile-header-info">
                    <a href="#">+998-90-777-05-12</a>
                </div>
            </div>
            <div class="mobile-social-icon">
                <h5 class="mb-15 text-grey-4">Bizni kuzatib boring</h5>
                <a href="#"><img src="{% static 'bookshop/imgs/theme/icons/icon-facebook.svg' %}" alt=""></a>
                <a href="#"><img src="{% static 'bookshop/imgs/theme/icons/icon-twitter.svg' %}" alt=""></a>
                <a href="#"><img src="{% static 'bookshop/imgs/theme/icons/icon-instagram.svg' %}" alt=""></a>
                <a href="#"><img src="{% static 'bookshop/imgs/theme/icons/icon-pinterest.svg' %}" alt=""></a>
                <a href="#"><img src="{% static 'bookshop/imgs/theme/icons/icon-youtube.svg' %}" alt=""></a>
            </div>
        </div>
    </div>
</div>

templates/_components/script.html
{% load static %}

 <!-- Vendor JS-->
<script src="{% static 'bookshop/js/vendor/modernizr-3.6.0.min.js' %}"></script>
<script src="{% static 'bookshop/js/vendor/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'bookshop/js/vendor/jquery-migrate-3.3.0.min.js' %}"></script>
<script src="{% static 'bookshop/js/vendor/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/slick.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/jquery.syotimer.min.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/wow.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/jquery-ui.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/perfect-scrollbar.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/magnific-popup.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/select2.min.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/waypoints.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/counterup.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/jquery.countdown.min.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/images-loaded.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/isotope.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/scrollup.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/jquery.vticker-min.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/jquery.theia.sticky.js' %}"></script>
<script src="{% static 'bookshop/js/plugins/jquery.elevatezoom.js' %}"></script>
<!-- Template  JS -->
<script src="{% static 'bookshop/js/main.js' %}"></script>
<script src="{% static 'bookshop/js/shop.js' %}"></script>
<script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

<script>
    function showToast(message, title = "Notification") {
        var toastId = 'toast-' + Math.random().toString(36).substring(2, 9);

        var toastHTML = `
        <div id="${toastId}" class="toast show" role="alert" aria-live="assertive" aria-atomic="true" style="max-height: 45px; background-color: #e2eaf7">
            <div class="toast-content">
                ${title}: ${message}
            </div>
        </div>`;

        document.getElementById('toast-container').insertAdjacentHTML('beforeend', toastHTML);

        // Remove toast after a few seconds
        setTimeout(() => {
            document.getElementById(toastId).remove();
        }, 3000);
    }


    function updateCart(event, action, productId) {
        event.preventDefault();

        var url = '/cart/' + productId + '/' + action + '/';
        fetch(url, {
            method: 'GET',
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
            }
        })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    const btn_minus = document.getElementById('btn_minus');
                    if (action === 'remove' && data.message === "Cartdan o'chirildi") {
                        btn_minus.disabled = true;
                    } else if (action === 'remove') {
                        btn_minus.disabled = false;
                    }

                    console.log(data.message);

                    showToast(data.message);

                    document.getElementById('cart-count_top').innerText = Object.keys(data.cart).length;
                    document.getElementById('cart-count_nav').innerText = Object.keys(data.cart).length;
                }
                if (data.cart[productId.toString()]) {
                    document.getElementById(`qty_val${productId}`).innerText = data.cart[productId.toString()];
                }else{
                    document.getElementById('qty_val${productId}').innerText = 0;
                }
            })
            .catch(error => console.log('Error:', error));
    }
</script>


<script>
    function transliterate(value) {
        const map = {
            'А': 'A', 'Б': 'B', 'В': 'V', 'Г': 'G', 'Д': 'D', 'Е': 'E', 'Ё': 'Yo', 'Ж': 'Zh', 'З': 'Z', 'И': 'I',
            'Й': 'Y', 'К': 'K', 'Л': 'L', 'М': 'M', 'Н': 'N', 'О': 'O', 'П': 'P', 'Р': 'R', 'С': 'S', 'Т': 'T',
            'У': 'U', 'Ф': 'F', 'Х': 'X', 'Ц': 'Ts', 'Ч': 'Ch', 'Ш': 'Sh', 'Щ': 'Shch', 'Ъ': '', 'Ы': 'Y',
            'Ь': '', 'Э': 'E', 'Ю': 'Yu', 'Я': 'Ya', 
            'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i',
            'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't',
            'у': 'u', 'ф': 'f', 'х': 'x', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'shch', 'ъ': '', 'ы': 'y',
            'ь': '', 'э': 'e', 'ю': 'yu', 'я': 'ya'
        };
        return value.split('').map(function(char) {
            return map[char] || char; 
        }).join('');
    }

    function createSlug(value) {
        return transliterate(value)     
            .toLowerCase()               
            .replace(/[^a-z0-9\s-]/g, '') 
            .replace(/\s+/g, '-')         
            .replace(/-+/g, '-');         
    }

    document.getElementById("id_title").addEventListener("input", function() {
        let title = this.value;
        let slugField = document.getElementById("id_slug");
        slugField.value = createSlug(title);  
    });
</script>

templates/_components/style.html
{% load static %}

<meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description"
          content="Onlayn kitob do'koni: bestsellerlar, yangi kitoblar va zamonaviy adabiyotlar. Chegirmalar va maxsus aksiyalar bilan xarid qiling.">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Ijtimoiy tarmoqlar uchun Open Graph metadata -->
    <meta property="og:title" content="Sevimli kitoblaringiz onlayn do'koni | Kitoblar do'koni">
    <meta property="og:type" content="website">
    <meta property="og:description"
          content="Ko'plab kitoblar bilan tanishing va chegirmalar bilan xarid qiling. Kategoriyalar bo'yicha kitoblarni o'rganing va sevimli mualliflaringizni toping.">
    <meta property="og:site_name" content="KitobDo'konim">

    <!-- Twitter Cards metadata -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Kitoblar dunyosini kashf eting | KitobDo'konim">
    <meta name="twitter:description"
          content="Bestsellerlardan tortib yangi kitoblargacha. Bizning onlayn kitob do'konimizda chegirmalar va maxsus aksiyalar bilan xarid qiling.">
    <!-- Rasm URL manzilini o'zingizga mos ravishda kiriting -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'bookshop/imgs/theme/favicon.svg' %}">
    <!-- Template CSS -->
    <link rel="stylesheet" href="{% static 'bookshop/css/main.css' %}">
    <style>
  #toast-container {
    position: fixed;
    top: 20px;
    right: 20px;
    z-index: 1050;
    display: flex;
    flex-direction: column;
    align-items: flex-end;
}

.toast {
    border-radius: 8px;
    padding: 10px 15px;
    margin-bottom: 10px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.6);
    animation: slide-in 0.5s ease-out;
    font-family: Arial, sans-serif;
    font-size: 14px;
}

.toast-content {
    font-size: 16px;
    color: #db910f;
}

@keyframes slide-in {
    from {
        opacity: 0;
        transform: translateY(20px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}
</style>