bookshop/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('book/list/', views.BookListView.as_view(), name='book_list'),
    path('book/<slug:slug>/detail/', views.BookDetailView.as_view(), name='book_detail'),

    path('book/create/', views.BookCreateView.as_view(), name='book_create'),
    path('book/<slug:slug>/update/', views.BookUpdateView.as_view(), name='book_update'),
    path('book/<slug:slug>/delete/', views.BookDeleteView.as_view(), name='book_delete'),

    path('cart/', views.CartListView.as_view(), name='cart_list'),
    path('cart/<int:pk>/add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/<int:pk>/remove/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/<int:pk>/delete/', views.CartDeleteView.as_view(), name='cart_delete'),

    path('product/<slug:slug>/comment/', views.CommentView.as_view(), name='comment'),


    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookshop.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/update/photo/', views.UpdateProfileImageView.as_view(), name='update_photo'),
    path('profile/update/password/', views.PasswordChangeView.as_view(), name='password_change'),
    path('profile/update/info/', views.UpdateProfileView.as_view(), name='update_info'),
    path('register/', views.Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.ActivateAccount.as_view(), name='activate'),
    path('activate/resend-activation/', views.ResendActivationEmail.as_view(), name='resend_activation_email'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

bookshop/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField

from user.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nomi")
    slug = models.SlugField(max_length=100, verbose_name="Slug")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan vaqti")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Kategoriya'
        verbose_name_plural = 'Kategoriyalar'


class Book(models.Model):
    title = models.CharField(max_length=200, verbose_name="Nomi")
    slug = models.SlugField(max_length=200, verbose_name="Slug")
    author = models.CharField(max_length=100, verbose_name="Muallif")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Kategoriya")
    publication_year = models.IntegerField(verbose_name="Yili")
    description = models.TextField(verbose_name="Tavsif")
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Narxi (so'm)")
    is_discount = models.BooleanField(default=False, verbose_name="Chegirmadami?")
    discount = models.DecimalField(max_digits=4, decimal_places=2, default=0, verbose_name="Chegirish qiymati (%)")
    image = models.ImageField(upload_to='books/', verbose_name="Rasmi")
    quantity = models.IntegerField(verbose_name="Soni")
    views = models.IntegerField(default=0, verbose_name="Ko'rishlar")
    is_featured = models.BooleanField(default=False, verbose_name="Tavsiya qilinsinmi?")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Yangilangan vaqti")
    full_description = RichTextField(null=True, blank=True, default="Yo'q", verbose_name="Tavsif")

    def __str__(self):
        return self.author + ' - ' + self.title

    def get_image(self):
        if self.image:
            return self.image.url
        return None

    class Meta:
        verbose_name = 'Kitob'
        verbose_name_plural = 'Kitoblar'
        ordering = ['-created_at']

    def current_price(self):
        if self.is_discount:
            return round(self.price * (1 - self.discount / 100), 2)
        return self.price

    def get_rating(self):
        comments = self.comment_set.all()
        if comments.exists():
            return '{:.2f}'.format(sum(comment.rating for comment in comments) / comments.count())
        return 0

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Book, self).save(*args, **kwargs)


class Comment(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name="Kitob")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Foydalanuvchi")
    rating = models.IntegerField(default=0, verbose_name="Baho")
    content = models.TextField(verbose_name="Izoh")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqtih")

    def __str__(self):
        return self.user.username +'-'+ self.book.title

    class Meta:
        verbose_name = 'Izoh'
        verbose_name_plural = 'Izohlar'

templates/components/books.html
{% load static %}

<section class="product-tabs section-padding wow fadeIn animated">
    <div class="container">
        <div class="tab-header">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="nav-tab-one" data-bs-toggle="tab" data-bs-target="#tavsiya"
                            type="button" role="tab" aria-controls="tab-one" aria-selected="true">Tavsiya
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="nav-tab-two" data-bs-toggle="tab" data-bs-target="#mashhur"
                            type="button" role="tab" aria-controls="tab-two" aria-selected="false">Mashhur
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="nav-tab-three" data-bs-toggle="tab" data-bs-target="#yangi"
                            type="button" role="tab" aria-controls="tab-three" aria-selected="false">Yangi
                    </button>
                </li>
                {% if request.user.is_authenticated and request.user.is_staff %}
                    <li class="nav-item" role="presentation">
                        <a href="{% url 'book:book_create' %}" class="nav-link"
                           type="button" role="tab" aria-controls="tab-three" aria-selected="false">Kitob qo'shish
                        </a>
                    </li>
                {% endif %} 
            </ul>
            <a href="{% url 'book:book_list' %}" class="view-more d-none d-md-flex">Barchasi<i
                    class="fi-rs-angle-double-small-right"></i></a>
        </div>
        <!--Tavsiya-->
        <div class="tab-content wow fadeIn animated" id="myTabContent">
            <div class="tab-pane fade show active" id="tavsiya" role="tabpanel" aria-labelledby="tab-one">
                <div class="row product-grid-4">
                    {% for book in featured_books %}
                        {% include 'bookshop/_components/book_card.html' %}
                    {% endfor %}

                </div>
                <!--End product-grid-4-->
            </div>
            <!--En tab one (Featured)-->
            <div class="tab-pane fade " id="mashhur" role="tabpanel" aria-labelledby="tab-one">
                <div class="row product-grid-4">
                    {% for book in popular_books %}
                        {% include 'bookshop/_components/book_card.html' %}
                    {% endfor %}

                </div>
                <!--End product-grid-4-->
            </div>
            <!--En tab two (Popular)-->
            <div class="tab-pane fade" id="yangi" role="tabpanel" aria-labelledby="tab-one">
                <div class="row product-grid-4">
                    {% for book in new_books %}
                        {% include 'bookshop/_components/book_card.html' %}
                    {% endfor %}

                </div>
                <!--End product-grid-4-->
            </div>
            <!--En tab three (New added)-->
        </div>

    </div>
</section>

templates/components/categories.html
{% load static %}

<section class="popular-categories section-padding mt-15 mb-4">
    <div class="container wow fadeIn animated">
        <h3 class="section-title mb-20"><span>Barcha</span> Kategoriyalar</h3>
        <div class="carausel-6-columns-cover position-relative">
            <div class="slider-arrow slider-arrow-2 carausel-6-columns-arrow" id="carausel-6-columns-arrows"></div>
            <div class="carausel-6-columns" id="carausel-6-columns">
                {% for category in categories %}
                    <div class="card-1">
                        <h5><a href="{% url 'book:book_list' %}?category={{ category.slug }}">{{ category }} ({{ category.book_set.all.count }})</a></h5>
                    </div>
                {% endfor %}
                
            </div>
        </div>
    </div>
</section>

templates/components/featured.html
{% load static %}

<section class="featured section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-4 mb-md-3 mb-lg-0">
                <div class="banner-features wow fadeIn animated hover-up animated">
                    <img src="{% static 'bookshop/imgs/theme/icons/feature-1.png' %}" alt="">
                    <h4 class="bg-1">Bepul Yetkazish</h4>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 mb-md-3 mb-lg-0">
                <div class="banner-features wow fadeIn animated hover-up animated">
                    <img src="{% static 'bookshop/imgs/theme/icons/feature-2.png' %}" alt="">
                    <h4 class="bg-3">Onlayn Buyurtma</h4>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 mb-md-3 mb-lg-0">
                <div class="banner-features wow fadeIn animated hover-up animated">
                    <img src="{% static 'bookshop/imgs/theme/icons/feature-3.png' %}" alt="">
                    <h4 class="bg-2">Tejang va Qidir</h4>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 mb-md-3 mb-lg-0">
                <div class="banner-features wow fadeIn animated hover-up animated">
                    <img src="{% static 'bookshop/imgs/theme/icons/feature-4.png' %}" alt="">
                    <h4 class="bg-4">Maxsus Takliflar</h4>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 mb-md-3 mb-lg-0">
                <div class="banner-features wow fadeIn animated hover-up animated">
                    <img src="{% static 'bookshop/imgs/theme/icons/feature-5.png' %}" alt="">
                    <h4 class="bg-5">Yaxshi Narxlar</h4>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 mb-md-3 mb-lg-0">
                <div class="banner-features wow fadeIn animated hover-up animated">
                    <img src="{% static 'bookshop/imgs/theme/icons/feature-6.png' %}" alt="">
                    <h4 class="bg-6">24/7 Call-center</h4>
                </div>
            </div>
        </div>
    </div>
</section>

templates/components/slider.html
{% load static %}

<section class="home-slider position-relative pt-25 pb-20">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 mb-3">
                <div class="position-relative">
                    <div class="hero-slider-1 style-3 dot-style-1 dot-style-1-position-1">
                        <div class="single-hero-slider single-animation-wrap">
                            <div class="container">
                                <div class="slider-1-height-3 slider-animated-1">
                                    <div class="hero-slider-content-2">
                                        <h4 class="animated">Chegirma Aksiyasi</h4>
                                        <h2 class="animated fw-900">Eng Qimmatli Takliflar</h2>
                                        <h1 class="animated fw-900 text-brand">Barcha Kitoblarda</h1>
                                        <p class="animated">Ko'proq tejang, kuponlar bilan 70% gacha chegirma</p>
                                        <a class="animated btn btn-brush btn-brush-3"
                                           href="{% url 'book:book_list' %}"> Hozir Sotib Oling </a>
                                    </div>
                                    <div class="slider-img">
                                        <img src="{% static 'bookshop/imgs/slider/evara-slider1.png' %}" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="single-hero-slider single-animation-wrap">
                            <div class="container">
                                <div class="slider-1-height-3 slider-animated-1">
                                    <div class="hero-slider-content-2">
                                        <h4 class="animated">Maxsus Takliflar</h4>
                                        <h2 class="animated fw-900">Kitoblar Yangiligi</h2>
                                        <h1 class="animated fw-900 text-brand">Ajoyib To'plamlar</h1>
                                        <p class="animated">Ko'proq tejang, kuponlar bilan 20% gacha chegirma</p>
                                        <a class="animated btn btn-brush btn-brush-3"
                                           href="{% url 'book:book_list' %}"> Hozir Sotib Oling </a>
                                    </div>
                                    <div class="slider-img">
                                        <img src="{% static 'bookshop/imgs/slider/evara-slider2.png' %}" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="slider-arrow hero-slider-1-arrow style-3"></div>
                </div>
            </div>
            <div class="col-lg-3 d-md-none d-lg-block">
                <div class="banner-img banner-1 wow fadeIn animated home-3">
                    <img class="border-radius-10" src="{% static 'bookshop/imgs/slider/right-top-slider.png' %}" alt="">
                    <div class="banner-text">
                        <span>Badiiy asarlar</span>
                        <h4>Kuzgi mavsumga 17% chegirma</h4>
                        <a href="{% url 'book:book_list' %}">Hozir Sotib Oling <i class="fi-rs-arrow-right"></i></a>
                    </div>
                </div>
                <div class="banner-img banner-2 wow fadeIn animated mb-0">
                    <img class="border-radius-10" src="{% static 'bookshop/imgs/banner/banner-7.jpg' %}" alt="">
                    <div class="banner-text">
                        <span>Romanlar</span>
                        <h4>O'zbek romanlariga 20% chegirma</h4>
                        <a href="{% url 'book:book_list' %}">Hozir Sotib Oling <i class="fi-rs-arrow-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>